apiVersion: v1
kind: Service
metadata:
  name: ticket-booking-service
spec:
  type: ClusterIP
  selector:
    app: ticket-booking
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
